[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="message" type="java.lang.String" --]
[#-- @ftlvariable name="user" type="ru.itmo.wp.domain.User" --]
[#-- @ftlvariable name="userr" type="ru.itmo.wp.domain.User" --]
[#-- @ftlvariable name="notices" type="java.util.List<ru.itmo.wp.domain.Notice>" --]
